import random
import copy
from time import time

from tqdm import tqdm
import islpy as isl
from collections import deque, defaultdict

from src.mapping.heuristic import *
from src.mapping.mapping import *

from src.utils.circuit_utils import *
from src.utils.isl_data_loader import *
from src.utils.isl_to_python import *
from src.utils.python_to_isl import *

from src.graph.graph import *
from qiskit.dagcircuit import DAGCircuit
from qiskit import QuantumRegister, ClassicalRegister
from qiskit.circuit.library import SwapGate
from qiskit.converters import circuit_to_dag, circuit_to_dagdependency
from qiskit.circuit import Instruction
from time import perf_counter


class Qlosure():
    def __init__(self, edges, data, use_isl=False, with_circuit=True) -> None:

        # Normalize edges as tuple pairs for O(1) checks
        self.backend_connections = set(tuple(edge) for edge in edges)
        # Build backend graph as adjacency list
        self.backend = build_backend_graph(edges)
        

        self.use_isl = use_isl
        self.with_circuit = with_circuit

        # Program meta data generated by qrane
        self.data = data

        # Precompute distances over the hardware graph
        self.distance_matrix = compute_distance_matrix(self.backend)

        self.num_physical_qubits = len(self.distance_matrix) 
        
        # Determine the maximum logical qubit requested by safely finding the max integer across all read/write nodes
        max_q = -1
        for gate_dict in (self.data.get("read", {}), self.data.get("write", {})):
            for qubits in gate_dict.values():
                if qubits:
                    max_q = max(max_q, max(qubits))
        self.num_logical_qubits = max_q + 1


        self.access, self.write_dict = self.data["read"], self.data["write"]
        self.macro_gates = self.data.get("macro_gates", {})
        self.access2q = None

        self.decay_parameter = [1 for _ in range(self.num_physical_qubits)]
        self.qubit_depth = {q: 0 for q in range(self.num_physical_qubits)}

        self.reset = 5
        self.isl_mapping = None
        self.mapping_dict = None
        self.reverse_mapping_dict = None
        self.front_layer = None
        self.extended_layer = None

        # **************************************************************************
        # Per-logical-qubit storage of single-qubit gates in FIFO order.
        # This is a list where index = logical qubit id and each element
        # is a collections.deque used to preserve the order of single-qubit
        # gates associated with that qubit.
        self.single_qubit_gates = [deque() for _ in range(self.num_physical_qubits)]

        self.filled_gaps = defaultdict(set)  # To track filled gaps for final insertion (depth, gate)

        self.dag = DAGCircuit() #So I don't have to use circuit_to_dag(Self.circuit) repeatedly

        # **************************************************************************

        if with_circuit:
            self.circuit = QuantumCircuit(self.num_physical_qubits)
            self.original_circuit = QuantumCircuit.from_qasm_str(
                data.get("qasm_code", ""))
            
        #**************************************************************************
        # Create quantum and classical registers
        qreg = QuantumRegister(self.num_physical_qubits, "q")
        creg = ClassicalRegister(self.num_physical_qubits, "c")

        # Add them to the DAG
        self.dag.add_qreg(self.circuit.qregs[0])
        #**************************************************************************

        self.results = {}
        self.instruction_times = defaultdict(int)

        self.count = 0
  
    def run(self, heuristic_method="qlosure", enforce_read_after_read=True, transitive_reduction=True, initial_mapping_method="new", dag_mode="default", num_iter=1, look_ahead_param=5, verbose=0):
        """
        Execute the mapping/scheduling loop and return (min_swaps, min_depth, exec_time).

        The method alternates between forward and backward DAG passes when
        num_iter > 1, keeping the best result across passes.
        """

        # Initialize the logical->physical mapping

        self.results = {}
        min_swaps = float('inf')
        min_depth = float('inf')

        # Build DAGs and a 2-qubit-only view of access for heuristics
        successors2q, dag_predecessors2q, successors_full, dag_predecessors_full, self.access2q = generate_dag(
            self.access, self.write_dict, self.num_physical_qubits, enforce_read_after_read, transitive_reduction)

        if not enforce_read_after_read and dag_mode == "hybrid":
            successors2q_rar_included, dag_predecessors2q_rar_included, _, _, _ = generate_dag(
                self.access, self.write_dict, self.num_physical_qubits, enforce_read_after_read=True, transitive_reduction=transitive_reduction)
        else:
            successors2q_rar_included = successors2q
            dag_predecessors2q_rar_included = dag_predecessors2q

        # Precompute dependency counts using our own implementation of the transitive closure
        dag_forward_dependencies_count = compute_transitive_closure_bitset(
            successors2q_rar_included, dag_predecessors2q_rar_included)

        if num_iter > 1:
            # dependency counts for the inverse of the DAG
            dag_backward_dependencies_count = compute_transitive_closure_bitset(
                dag_predecessors2q_rar_included, successors2q_rar_included)
        else:
            dag_backward_dependencies_count = dag_forward_dependencies_count

        # Alternate forward/backward when num_iter>1. Keep best
        for i in range(2*(num_iter-1)+1):
            if i % 2 == 0:
                self.dag_dependencies_count = dag_forward_dependencies_count
                self.dag2q = successors2q
                self.dag_predecessors2q = dag_predecessors2q
                self.dag2q_restricted = successors2q_rar_included
                self.dag_predecessors2q_restricted = dag_predecessors2q_rar_included
                self.dag_full = successors_full
                self.dag_predecessors_full = copy.deepcopy(
                    dag_predecessors_full) if num_iter > 1 else dag_predecessors_full
            else:
                self.dag_dependencies_count = dag_backward_dependencies_count
                self.dag2q = dag_predecessors2q
                self.dag_predecessors2q = successors2q
                self.dag2q_restricted = dag_predecessors2q_rar_included
                self.dag_predecessors2q_restricted = successors2q_rar_included
                self.dag_full = dag_predecessors_full
                self.dag_predecessors_full = copy.deepcopy(
                    successors_full) if num_iter > 1 else successors_full
            
            self.init_mapping(method=initial_mapping_method)

            self.init_front_layer()
            self.qubit_depth = {q: 0 for q in range(self.num_physical_qubits)}
            start = time()
            swap_count = self.execute_algorithm(
                heuristic_method, look_ahead_param, verbose)
            exec_time = time()-start
            if i % 2 == 0:
                if swap_count < min_swaps:
                    min_swaps = min(min_swaps, swap_count)
                    min_depth = min(min_depth, self.get_circuit_depth())
                elif swap_count == min_swaps:
                    min_depth = min(min_depth, self.get_circuit_depth())

        return min_swaps, min_depth, exec_time
 
    def init_mapping(self, method="new"):
        if method == "random":
            initial_mapping = generate_random_initial_mapping(
                self.num_physical_qubits)
        elif method == "trivial":
            initial_mapping = generate_trivial_initial_mapping(
                self.num_logical_qubits)
        elif method == "sabre":
            initial_mapping = generate_sabre_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_physical_qubits)
        elif method == "new":
            initial_mapping = self.generate_New_method_initial_mapping(
                self.distance_matrix, self.num_physical_qubits, self.num_logical_qubits, backend=self.backend, backend_connections=self.backend_connections, access=self.access, dag_dependencies_count=self.dag_dependencies_count, dag2q=self.dag2q, dag_predecessors2q=self.dag_predecessors2q)
        else:
            raise ValueError(
                f"Unknown mapping initialization method: {method}")
    
        self.mapping_dict, self.reverse_mapping_dict = self.generate_clean_mapping(initial_mapping)

        if self.use_isl:
            self.isl_mapping = dict_to_isl_map(self.mapping_dict)
        

    def generate_clean_mapping(self,mapping):
        """
        Generate the reverse mapping from physical qubits to logical qubits.
        - reverse_mapping[physical] = logical
        """
        cleaned_initial_mapping =  [-1] * self.num_physical_qubits
        for logical_q, physical_q in enumerate(mapping):
            if 0 <= logical_q < self.num_logical_qubits:
                cleaned_initial_mapping[logical_q] = physical_q


        # Generate reverse mapping from initial_mapping
        cleaned_reverse_initial_mapping = [-1] * self.num_physical_qubits

        for logical_q, physical_q in enumerate(cleaned_initial_mapping):
            if 0 <= physical_q < len(cleaned_reverse_initial_mapping):
                if cleaned_reverse_initial_mapping[physical_q] == -1:
                    cleaned_reverse_initial_mapping[physical_q] = logical_q

        return cleaned_initial_mapping, cleaned_reverse_initial_mapping

    def init_front_layer(self):
        self.front_layer = set()
        for gate in self.dag_full:
            if len(self.dag_predecessors_full[gate]) == 0:
                self.front_layer.add(gate)

    def execute_algorithm(self, huristic_method, param, verbose):
        swap_count = 0
        total_gates = len(self.access)
        self.decay_parameter = [1 for _ in range(self.num_physical_qubits)]

        with tqdm(total=total_gates, desc="Running Qlosure", mininterval=0.1, disable=(verbose == 0), leave=True) as pbar:
            while len(self.front_layer) > 0:

                ready_to_execute_gates = self.extract_ready_to_execute_gate_list()
                if len(ready_to_execute_gates) > 0:

                    self.update_front_layer(
                        ready_to_execute_gates)

                    self.decay_parameter = [1 for _ in range(self.num_physical_qubits)]
                    pbar.update(len(ready_to_execute_gates))

                else:

                    local_swap_count = self.apply_heuristic(
                        huristic_method, param, verbose=verbose)

                    swap_count += local_swap_count

        return swap_count    

    def extract_ready_to_execute_gate_list(self,):
        ready_to_execute_gates_list = []

        for gate in self.front_layer:
            if self.is_gate_executable(gate):
                ready_to_execute_gates_list.append(gate)

        return ready_to_execute_gates_list

    def is_gate_executable(self, gate) -> bool:
        if len(self.access[gate]) == 1:
            q = self.access[gate][0]
            phys_q = self.mapping_dict[q]
            new_depth = self.qubit_depth.get(phys_q, 0) + 1
            self.qubit_depth[phys_q] = new_depth
            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit,self.mapping_dict)

            return True

        q1, q2 = self.access[gate]
        phys_q1, phys_q2 = self.mapping_dict[q1], self.mapping_dict[q2]

        if (phys_q1, phys_q2) in self.backend_connections or (phys_q2, phys_q1) in self.backend_connections:
            current_depth_q1 = self.qubit_depth.get(phys_q1, 0)
            current_depth_q2 = self.qubit_depth.get(phys_q2, 0)
            new_depth = max(current_depth_q1, current_depth_q2) + 1

            self.qubit_depth[phys_q1] = new_depth
            self.qubit_depth[phys_q2] = new_depth

            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit,self.mapping_dict)

            return True
        return False

    def update_front_layer(self, executable_gates):
        for gate in executable_gates:
            for successor_gate in self.dag_full[gate]:
                self.dag_predecessors_full[successor_gate].discard(gate)
                if len(self.dag_predecessors_full[successor_gate]) == 0:
                    self.front_layer.add(successor_gate)

            self.front_layer.discard(gate)

    def apply_heuristic(self, huristic_method, param, verbose=0):
        if huristic_method not in ["qlosure"]:
            raise ValueError(
                f"Invalid heuristic method provided {huristic_method}. ")

        if huristic_method == "qlosure":
            return self._apply_qlosure_score_heuristic(param)


    def _apply_qlosure_score_heuristic(self, param):
        logical_qubits = [
            q for gate in self.front_layer for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, extended_layer_index = create_leveled_extended_successor_set(
            self.front_layer, self.dag2q_restricted, self.access2q, len(
                physical_qubits)*param
        )

        candidate_swaps = generate_swap_candidates(
            physical_qubits, self.backend)

        heuristic_score = {}
        for swap_gate in candidate_swaps:
            temp_mapping_dict = swap_logical_physical_mappings(
                self.mapping_dict, self.reverse_mapping_dict, swap_gate
            )

            score = qlosure_poly_heuristic(self.front_layer, self.extended_layer, temp_mapping_dict,
                                           self.distance_matrix, self.access2q, self.decay_parameter, self.dag_dependencies_count, extended_layer_index, swap_gate)
            heuristic_score[swap_gate] = score

        best_swap_gate = find_min_score_swap_gate(heuristic_score)

        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(
                self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(
            self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True
        )

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1

    def update_depth(self, q1, q2):

        current_depth_q1 = self.qubit_depth.get(q1, 0)
        current_depth_q2 = self.qubit_depth.get(q2, 0)
        new_depth = max(current_depth_q1, current_depth_q2) + 1

        self.qubit_depth[q1] = new_depth
        self.qubit_depth[q2] = new_depth

        if self.with_circuit:
            self.circuit.swap(q1, q2)

    def get_circuit_depth(self):
        return max(self.qubit_depth.values())
    
    def generate_New_method_initial_mapping(self, distance_matrix, num_physical_qubits, num_logical_qubits, backend, backend_connections, access, dag_dependencies_count, dag2q, dag_predecessors2q):
        """
        Generate an initial mapping from logical qubits to physical qubits on the hardware backend.

        Available attributes:
        - distance_matrix: List[List[int]] : All-pairs shortest-path distances on the hardware graph.
        - num_physical_qubits: int : Total number of PHYSICAL qubits on the backend (e.g. 127 for ibm_sherbrooke).
                                    WARNING: This is NOT the circuit size. Most circuits use far fewer qubits.
        
                                    This is the size of the mapping you need to optimise.
        - num_logical_qubits: int : Total number of LOGICAL qubits in the circuit.
        - backend: DefaultDict[int, Set[int]] : Hardware adjacency list (physical qubit -> set of connected physical qubits).
        - backend_connections: Set[Tuple[int, int]] : Set of hardware edges for O(1) adjacency checks.
        - access: Dict[int, List[int]] : Maps each gate ID to a list of the LOGICAL qubit indices it acts on.
                                        Iterate over access.values() to enumerate qubit interactions.
        - dag_dependencies_count: List[int] : Criticality score per gate (transitive closure).
        - dag2q: Dict[int, Set[int]] : Gate successors in the 2-qubit DAG.
        - dag_predecessors2q: Dict[int, Set[int]] : Gate predecessors in the 2-qubit DAG.

        Returns:
        - mapping: List[int] of length num_physical_qubits : mapping[logical_qubit] = physical_qubit

        IMPORTANT: You must assign a distinct physical qubit to every logical qubit 0..num_logical_qubits-1.
                Only entries mapping[0..num_logical_qubits-1] affect circuit performance; the rest can stay trivial.
        """

        mapping = [-1] * num_physical_qubits          # mapping[i] = -1 (unassigned)
        for logical_qubit in range(num_logical_qubits):
            mapping[logical_qubit] = logical_qubit  # Initial trivial mapping (logical i -> physical i)
        return mapping
