import random
import copy
from time import time
from tqdm import tqdm
import islpy as isl
import sys
import os
# Ensure the quantum_mapping root is on sys.path so src.* imports resolve
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
from src.mapping.heuristic import *
from src.mapping.mapping import *
from src.utils.circuit_utils import *
from src.utils.isl_data_loader import *
from src.graph.graph import *
import math

class Qlosure():
    def __init__(self, edges, data, use_isl=False, with_circuit=True) -> None:

        # Normalize edges as tuple pairs for O(1) checks
        self.backend_connections = set(tuple(edge) for edge in edges)
        # Build backend graph as adjacency list
        self.backend = build_backend_graph(edges)
        self.use_isl = use_isl
        self.with_circuit = with_circuit
        # Program meta data generated by qrane
        self.data = data
        # Precompute distances over the hardware graph
        self.distance_matrix = compute_distance_matrix(self.backend)
        # Number of physical qubits. Keep this aligned with distance_matrix indexing.
        self.num_qubits = len(self.distance_matrix)
        # A dictionary mapping each gate to a list of the qubits it acts upon
        self.access, self.write_dict = self.data["read"], self.data["write"]
        # Number of logical qubits actually used in this circuit (NOT the same as num_qubits)
        _logical_qubits_used = set(q for qubits in self.access.values() for q in qubits)
        self.num_logical_qubits = len(_logical_qubits_used)
        self.macro_gates = self.data.get("macro_gates", {})
        self.access2q = None
        self.decay_parameter = [1 for _ in range(self.num_qubits)]
        self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
        self.reset = 5
        self.isl_mapping = None
        self.mapping_dict = None
        self.reverse_mapping_dict = None
        self.front_layer = None
        self.extended_layer = None
        
        # DAG-related attributes initialized to None; set during run() before initial mapping generation
        self.dag_dependencies_count = None
        self.dag2q = None
        self.dag_predecessors2q = None
        self.dag2q_restricted = None
        self.dag_predecessors2q_restricted = None
        self.dag_full = None
        self.dag_predecessors_full = None
        self.extended_layer_index = None
        self.temp_mapping_dict = None

        if with_circuit:
            self.circuit = QuantumCircuit(self.num_qubits)
            self.original_circuit = QuantumCircuit.from_qasm_str(data.get("qasm_code", ""))

        self.results = {}
        self.instruction_times = defaultdict(int)

    def prepare_initial_mapping_context(self, enforce_read_after_read=True, transitive_reduction=True, dag_mode="default"):
        """
        Build DAG/access metadata required by generated initial-mapping heuristics.
        This mirrors the forward-pass context setup done in run() so heuristics can be
        safely pre-tested before executing the full routing loop.
        """
        successors2q, dag_predecessors2q, successors_full, dag_predecessors_full, self.access2q = generate_dag(
            self.access,
            self.write_dict,
            self.num_qubits,
            enforce_read_after_read,
            transitive_reduction,
        )

        if not enforce_read_after_read and dag_mode == "hybrid":
            successors2q_rar_included, dag_predecessors2q_rar_included, _, _, _ = generate_dag(
                self.access,
                self.write_dict,
                self.num_qubits,
                enforce_read_after_read=True,
                transitive_reduction=transitive_reduction,
            )
        else:
            successors2q_rar_included = successors2q
            dag_predecessors2q_rar_included = dag_predecessors2q

        self.dag_dependencies_count = compute_transitive_closure_bitset(
            successors2q_rar_included,
            dag_predecessors2q_rar_included,
        )
        self.dag2q = successors2q
        self.dag_predecessors2q = dag_predecessors2q
        self.dag2q_restricted = successors2q_rar_included
        self.dag_predecessors2q_restricted = dag_predecessors2q_rar_included
        self.dag_full = successors_full
        self.dag_predecessors_full = dag_predecessors_full

        # Logical qubits are derived from active 2-qubit gate accesses in the prepared DAG view.
        self.num_logical_qubits = len(
            set(
                q
                for gate in self.dag_full
                if gate < len(self.access2q) and self.access2q[gate]
                for q in self.access2q[gate]
            )
        )

    def run(self, heuristic_method="Qlosure", enforce_read_after_read=True, transitive_reduction=True, initial_mapping_method="new_method", dag_mode="default", num_iter=1, look_ahead_param=5, verbose=0):
        """
        Execute the mapping/scheduling loop and return (min_swaps, min_depth, exec_time).
        The method alternates between forward and backward DAG passes when
        num_iter > 1, keeping the best result across passes.
        """

        self.results = {}
        min_swaps = float('inf')
        min_depth = float('inf')

        # Build DAGs and a 2-qubit-only view of access for heuristics
        successors2q, dag_predecessors2q, successors_full, dag_predecessors_full, self.access2q = generate_dag(self.access, self.write_dict, self.num_qubits, enforce_read_after_read, transitive_reduction)

        if not enforce_read_after_read and dag_mode == "hybrid":
            successors2q_rar_included, dag_predecessors2q_rar_included, _, _, _ = generate_dag(self.access, self.write_dict, self.num_qubits, enforce_read_after_read=True, transitive_reduction=transitive_reduction)
        else:
            successors2q_rar_included = successors2q
            dag_predecessors2q_rar_included = dag_predecessors2q

        # Precompute dependency counts using our own implementation of the transitive closure
        dag_forward_dependencies_count = compute_transitive_closure_bitset(successors2q_rar_included, dag_predecessors2q_rar_included)

        if num_iter > 1:
            # dependency counts for the inverse of the DAG
            dag_backward_dependencies_count = compute_transitive_closure_bitset(dag_predecessors2q_rar_included, successors2q_rar_included)
        else:
            dag_backward_dependencies_count = dag_forward_dependencies_count

        # Alternate forward/backward when num_iter>1. Keep best
        for i in range(2*(num_iter-1)+1):
            if i % 2 == 0:
                self.dag_dependencies_count = dag_forward_dependencies_count
                self.dag2q = successors2q
                self.dag_predecessors2q = dag_predecessors2q
                self.dag2q_restricted = successors2q_rar_included
                self.dag_predecessors2q_restricted = dag_predecessors2q_rar_included
                self.dag_full = successors_full
                self.dag_predecessors_full = copy.deepcopy(dag_predecessors_full) if num_iter > 1 else dag_predecessors_full
            else:
                self.dag_dependencies_count = dag_backward_dependencies_count
                self.dag2q = dag_predecessors2q
                self.dag_predecessors2q = successors2q
                self.dag2q_restricted = dag_predecessors2q_rar_included
                self.dag_predecessors2q_restricted = successors2q_rar_included
                self.dag_full = dag_predecessors_full
                self.dag_predecessors_full = copy.deepcopy(successors_full) if num_iter > 1 else successors_full
            
            self.apply_initial_mapping(initial_mapping_method)

            if self.use_isl:
                self.isl_mapping = dict_to_isl_map(self.mapping_dict)

            self.init_front_layer()
            self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
            start = time()
            swap_count = self.execute_algorithm(
                heuristic_method, look_ahead_param, verbose)
            exec_time = time()-start
            if i % 2 == 0:
                if swap_count < min_swaps:
                    min_swaps = min(min_swaps, swap_count)
                    min_depth = min(min_depth, self.get_circuit_depth())
                elif swap_count == min_swaps:
                    min_depth = min(min_depth, self.get_circuit_depth())

        return min_swaps, min_depth, exec_time       

    
        
    def init_front_layer(self):
        self.front_layer = set()
        for gate in self.dag_full:
            if len(self.dag_predecessors_full[gate]) == 0:
                self.front_layer.add(gate)
    
    def execute_algorithm(self, huristic_method, param, verbose):
        swap_count = 0
        total_gates = len(self.access)
        self.decay_parameter = [1 for _ in range(self.num_qubits)]

        with tqdm(total=total_gates, desc="Running Qlosure", mininterval=0.1, disable=(verbose == 0), leave=True) as pbar:
            while len(self.front_layer) > 0:

                ready_to_execute_gates = self.extract_ready_to_execute_gate_list()
                if len(ready_to_execute_gates) > 0:

                    self.update_front_layer(
                        ready_to_execute_gates)

                    self.decay_parameter = [1 for _ in range(self.num_qubits)]
                    pbar.update(len(ready_to_execute_gates))

                else:

                    local_swap_count = self.apply_qlosure_heuristic(param)

                    swap_count += local_swap_count

        return swap_count 

    def extract_ready_to_execute_gate_list(self,):
        ready_to_execute_gates_list = []

        for gate in self.front_layer:
            if self.is_gate_executable(gate):
                ready_to_execute_gates_list.append(gate)

        return ready_to_execute_gates_list

    def is_gate_executable(self, gate) -> bool:
        if len(self.access[gate]) == 1:
            q = self.access[gate][0]
            phys_q = self.mapping_dict[q]
            new_depth = self.qubit_depth.get(phys_q, 0) + 1
            self.qubit_depth[phys_q] = new_depth
            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True

        q1, q2 = self.access[gate]
        phys_q1, phys_q2 = self.mapping_dict[q1], self.mapping_dict[q2]

        if (phys_q1, phys_q2) in self.backend_connections or (phys_q2, phys_q1) in self.backend_connections:
            current_depth_q1 = self.qubit_depth.get(phys_q1, 0)
            current_depth_q2 = self.qubit_depth.get(phys_q2, 0)
            new_depth = max(current_depth_q1, current_depth_q2) + 1

            self.qubit_depth[phys_q1] = new_depth
            self.qubit_depth[phys_q2] = new_depth

            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True
        return False

    def update_front_layer(self, executable_gates):
        for gate in executable_gates:
            for successor_gate in self.dag_full[gate]:
                self.dag_predecessors_full[successor_gate].discard(gate)
                if len(self.dag_predecessors_full[successor_gate]) == 0:
                    self.front_layer.add(successor_gate)

            self.front_layer.discard(gate)
            
    def update_depth(self, q1, q2):

        current_depth_q1 = self.qubit_depth.get(q1, 0)
        current_depth_q2 = self.qubit_depth.get(q2, 0)
        new_depth = max(current_depth_q1, current_depth_q2) + 1

        self.qubit_depth[q1] = new_depth
        self.qubit_depth[q2] = new_depth

        if self.with_circuit:
            self.circuit.swap(q1, q2)

    def get_circuit_depth(self):
        return max(self.qubit_depth.values())

    def apply_qlosure_heuristic(self, param):

        logical_qubits = [q for gate in self.front_layer if gate < len(self.access2q) and self.access2q[gate] for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, self.extended_layer_index = create_leveled_extended_successor_set(self.front_layer, self.dag2q_restricted, self.access2q, len(physical_qubits)*param)

        candidate_swaps = generate_swap_candidates(physical_qubits, self.backend)
        
        if not candidate_swaps:
            raise RuntimeError(f"No swap candidates available! Physical qubits: {physical_qubits}, Backend edges: {len(self.backend_connections)}")

        heuristic_score = {}
        for swap_gate in candidate_swaps:
            self.temp_mapping_dict = swap_logical_physical_mappings(self.mapping_dict, self.reverse_mapping_dict, swap_gate)

            score = self.qlosure_poly_heuristic(swap_gate)
            heuristic_score[swap_gate] = score

        best_swap_gate = find_min_score_swap_gate(heuristic_score)

        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True)

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1

    def apply_initial_mapping(self, method="new_method"):

        # Normalize user-provided method names (e.g., "New_method", "new-method", " new_method ").
        method_key = str(method).strip().lower().replace("-", "_")

        if method_key in {"new_method", "newmethod", "custom"}:
            result = self.generate_New_method_initial_mapping(
                self.distance_matrix,
                self.num_qubits,
                self.backend,
                self.backend_connections,
                self.access,
                self.dag_dependencies_count,
                self.dag2q,
                self.dag_predecessors2q
            )
            
            # Safeguard: check if result is None
            if result is None:
                raise ValueError("generate_New_method_initial_mapping() returned None. Function must return (mapping_list, reverse_mapping_list).")
            
            try:
                self.mapping_dict, self.reverse_mapping_dict = result
            except (TypeError, ValueError) as e:
                raise ValueError(f"generate_New_method_initial_mapping() must return a tuple (list, list), got {type(result).__name__}: {e}")
            
            # Safeguard: check that we got valid lists
            if not isinstance(self.mapping_dict, list) or not isinstance(self.reverse_mapping_dict, list):
                raise ValueError(f"Mapping must be (list, list), got ({type(self.mapping_dict).__name__}, {type(self.reverse_mapping_dict).__name__})")
                
        elif method_key == "random":
            self.mapping_dict, self.reverse_mapping_dict = generate_random_initial_mapping(self.num_qubits)
        elif method_key == "trivial":
            self.mapping_dict, self.reverse_mapping_dict = generate_trivial_initial_mapping(self.num_qubits)
        elif method_key == "sabre":
            self.mapping_dict, self.reverse_mapping_dict = generate_sabre_initial_mapping(
                self.data["qasm_code"],
                self.backend_connections,
                self.num_qubits,
            )
        else:
            raise ValueError(f"Unknown mapping initialization method: {method}")

        if self.use_isl:
            self.isl_mapping = dict_to_isl_map(self.mapping_dict)

    def generate_New_method_initial_mapping(self, distance_matrix, num_qubits, backend, backend_connections, access, dag_dependencies_count, dag2q, dag_predecessors2q):
        
        pass  # This method will be dynamically replaced by the LLM-generated heuristic during evaluation.

################################################################################################################################################################
#                                                                  Qlosure Cost Function                                                                       #
################################################################################################################################################################    
    def qlosure_poly_heuristic(self, swap_gate):
        W = 1
        front_layer_size = len(self.front_layer)
        extended_layer_size = len(self.extended_layer)

        max_decay = max(self.decay_parameter[swap_gate[0]], self.decay_parameter[swap_gate[1]])

        f_distance = 0

        for g in self.front_layer:
            if g >= len(self.access2q) or not self.access2q[g]:
                continue
            q1, q2 = self.access2q[g]
            Q1, Q2 = self.temp_mapping_dict[q1], self.temp_mapping_dict[q2]
            deps = self.dag_dependencies_count[g]

            f_distance += (deps+1) * self.distance_matrix[Q1][Q2]

        e_distance = 0
        for g in self.extended_layer:
            if g >= len(self.access2q) or not self.access2q[g]:
                continue
            q1, q2 = self.access2q[g]
            Q1, Q2 = self.temp_mapping_dict[q1], self.temp_mapping_dict[q2]
            layer_factor = self.extended_layer_index.get(g, 0) + 1

            deps = self.dag_dependencies_count[g]
            e_distance += (deps+1) * \
                self.distance_matrix[Q1][Q2] * 1/layer_factor

        if front_layer_size == 0 or extended_layer_size == 0:
            # Avoid division by zero if all gates were filtered out
            H = 0
        else:
            H = max_decay * (f_distance / front_layer_size + W *
                            ((e_distance / extended_layer_size) if extended_layer_size else 0))

        return H
################################################################################################################################################################