# Module Name: PartEvo
# Last Revision: 2026/3/8
# This file is part of the LLM4AD project (https://github.com/Optima-CityU/llm4ad).
#
# Reference:
#   - Qinglong Hu and Qingfu Zhang.
#       "Partition to evolve: Niching-enhanced evolution with llms for automated algorithm discovery."
#       In Thirty-ninth Annual Conference on Neural Information Processing Systems (NeurIPS). 2025.
#
# ------------------------------- Copyright --------------------------------
# Copyright (c) 2025 Optima Group.
#
# Permission is granted to use the LLM4AD platform for research purposes.
# All publications, software, or other works that utilize this platform
# or any part of its codebase must acknowledge the use of "LLM4AD" and
# cite the following reference:
#
# Fei Liu, Rui Zhang, Zhuoliang Xie, Rui Sun, Kai Li, Xi Lin, Zhenkun Wang,
# Zhichao Lu, and Qingfu Zhang, "LLM4AD: A Platform for Algorithm Design
# with Large Language Model," arXiv preprint arXiv:2412.17287 (2024).
#
# For inquiries regarding commercial use or licensing, please contact
# http://www.llm4ad.com/contact.html
# --------------------------------------------------------------------------

from __future__ import annotations

import re
from typing import Tuple, List, Dict

from .prompt import PartEvoPrompt
from ...base import LLM, SampleTrimmer, Function, Program


class PartEvoSampler:
    """
    The MLESSampler serves as the interface for interacting with the LLM.
    It handles the execution of sampling requests and uses regular expressions
    to extract structured thoughts, image descriptions, and executable code
    from raw LLM text outputs.
    """
    def __init__(self, sampler: LLM, template_program: str | Program):
        """
        Initialize the sampler with an LLM engine and a code template.

        :param sampler: The LLM instance used to generate responses.
        :param template_program: A template structure used to reconstruct
                                 Function objects from raw code strings.
        """
        self._sampler = sampler
        self._template_program = template_program

    def get_thought_and_function_and_time(self, prompt: str, image64s: List = None, messages: List = None) -> tuple[
        str | None, Function | None, str, float | None]:
        """
        Main sampling method: Sends a prompt to the LLM and extracts both
        the algorithmic reasoning (thought) and the resulting code.

        :return: A tuple containing (extracted_thought, Function_object, raw_response_string, prompt_time).
        """
        import time
        # Call the LLM to get a raw response
        prompt_start_time = time.time()
        response = self._sampler.draw_sample(prompt, image64s=image64s, messages=messages)
        prompt_time = time.time() - prompt_start_time
        
        # Capture token counts from LLM if available
        prompt_tokens = getattr(self._sampler, 'last_prompt_tokens', None)
        completion_tokens = getattr(self._sampler, 'last_completion_tokens', None)
        thinking_tokens = getattr(self._sampler, 'last_thinking_tokens', 0)
        
        # Parse the algorithmic concept (thought) from the response
        thought = self.__class__.trim_thought_from_response(response)
        # Extract the code block and convert it into an executable Function instance
        code = SampleTrimmer.trim_preface_of_function(response)
        function = SampleTrimmer.sample_to_function(code, self._template_program)
        
        # Attach token counts to the function object
        if function is not None:
            function.prompt_tokens = prompt_tokens
            function.completion_tokens = completion_tokens
            function.thinking_tokens = thinking_tokens

        return thought, function, response, prompt_time

    def get_thought_and_function(self, prompt: str, image64s: List = None, messages: List = None) -> tuple[
        str | None, Function | None, str]:
        thought, function, response, prompt_time = self.get_thought_and_function_and_time(prompt, image64s, messages)
        return thought, function, response

    def get_image_description(self, prompt: str, image64s: List = None, messages: List = None):
        """
        Used for multimodal feedback loops. Extracts a textual analysis of
        visual data (e.g., control trajectories) generated by the LLM.

        :return: A tuple containing (extracted_description, raw_response_string).
        """
        response = self._sampler.draw_sample(prompt, image64s=image64s, messages=messages)
        # Parse descriptions specifically wrapped in double curly braces
        description = self.__class__.trim_description_from_response(response)
        return description, response

    def get_reflection(self, prompt: str, messages: List = None):
        response = self._sampler.draw_sample(prompt, image64s=None, messages=messages)
        # Parse descriptions specifically wrapped in double curly braces
        reflection = self.__class__.trim_reflection_from_response(response)
        return reflection

    def get_summary(self, prompt: str, messages: List = None):
        response = self._sampler.draw_sample(prompt, image64s=None, messages=messages)
        # Parse descriptions specifically wrapped in double curly braces
        summary = self.__class__.trim_summary_from_response(response)
        return summary

    @classmethod
    def trim_thought_from_response(cls, response: str) -> str | None:
        """
        Extracts content within <concept>...</concept> tags.
        This corresponds to the 'algorithmic concept' requested in the Prompt.
        """
        try:
            pattern = r'<concept>(.*?)</concept>'
            match = re.search(pattern, response, re.DOTALL)

            if match:
                return match.group(1).strip()
            return None
        except Exception as e:
            print(f"Error in trim_thought_from_response: {e}")
            return None

    @classmethod
    def trim_reflection_from_response(cls, response: str) -> str | None:
        """
        Extracts the content inside <reflection>...</reflection> tags.
        """
        try:
            pattern = r'<reflection>(.*?)</reflection>'
            match = re.search(pattern, response, re.DOTALL)
            if match:
                return match.group(1).strip()
            return None
        except Exception as e:
            print(f"Error in trim_reflection_from_response: {e}")
            return None

    @classmethod
    def trim_summary_from_response(cls, response: str) -> str | None:
        """
        Extracts the content inside <reflection>...</reflection> tags.
        """
        try:
            pattern = r'<summary>(.*?)</summary>'
            match = re.search(pattern, response, re.DOTALL)
            if match:
                return match.group(1).strip()
            return None
        except Exception as e:
            print(f"Error in trim_summary_from_response: {e}")
            return None

    @classmethod
    def trim_description_from_response(cls, response: str) -> str | None:
        """
        Extracts content within <description>...</description> tags.
        Used for multi-line textual descriptions of visual results.
        """
        try:
            pattern = r'<description>(.*?)</description>'
            match = re.search(pattern, response, re.DOTALL)
            if match:
                return match.group(1).strip()
            return None
        except Exception as e:
            print(f"Error in trim_description_from_response: {e}")
            return None
