import random
import copy
from time import time
from tqdm import tqdm
import islpy as isl
from src.mapping.heuristic import *
from src.mapping.mapping import *
from src.utils.circuit_utils import *
from src.utils.isl_data_loader import *
from src.graph.graph import *
import math

class Qlosure():
    def __init__(self, edges, data, use_isl=False, with_circuit=True) -> None:

        # Normalize edges as tuple pairs for O(1) checks
        self.backend_connections = set(tuple(edge) for edge in edges)
        # Build backend graph as adjacency list
        self.backend = build_backend_graph(edges)
        self.use_isl = use_isl
        self.with_circuit = with_circuit
        # Program meta data generated by qrane
        self.data = data
        # Precompute distances over the hardware graph
        self.distance_matrix = compute_distance_matrix(self.backend)
        # Number of physical qubits
        self.num_qubits = len(self.distance_matrix) + 1
        # A dictionary mapping each gate to a list of the qubits it acts upon
        self.access, self.write_dict = self.data["read"], self.data["write"]
        self.macro_gates = self.data.get("macro_gates", {})
        self.access2q = None
        self.decay_parameter = [1 for _ in range(self.num_qubits)]
        self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
        self.reset = 5
        self.isl_mapping = None
        self.mapping_dict = None
        self.reverse_mapping_dict = None
        self.front_layer = None
        self.extended_layer = None

        if with_circuit:
            self.circuit = QuantumCircuit(self.num_qubits - 1)
            self.original_circuit = QuantumCircuit.from_qasm_str(data.get("qasm_code", ""))

        self.results = {}
        self.instruction_times = defaultdict(int)

    def run(self, heuristic_method="Qlosure", enforce_read_after_read=True, transitive_reduction=True, initial_mapping_method="trivial", dag_mode="default", num_iter=1, look_ahead_param=5, verbose=0):
        """
        Execute the mapping/scheduling loop and return (min_swaps, min_depth, exec_time).
        The method alternates between forward and backward DAG passes when
        num_iter > 1, keeping the best result across passes.
        """

        # Initialize the logical->physical mapping
        self.init_mapping()

        self.results = {}
        min_swaps = float('inf')
        min_depth = float('inf')

        # Build DAGs and a 2-qubit-only view of access for heuristics
        successors2q, dag_predecessors2q, successors_full, dag_predecessors_full, self.access2q = generate_dag(self.access, self.write_dict, self.num_qubits, enforce_read_after_read, transitive_reduction)

        if not enforce_read_after_read and dag_mode == "hybrid":
            successors2q_rar_included, dag_predecessors2q_rar_included, _, _, _ = generate_dag(self.access, self.write_dict, self.num_qubits, enforce_read_after_read=True, transitive_reduction=transitive_reduction)
        else:
            successors2q_rar_included = successors2q
            dag_predecessors2q_rar_included = dag_predecessors2q

        # Precompute dependency counts using our own implementation of the transitive closure
        dag_forward_dependencies_count = compute_transitive_closure_bitset(successors2q_rar_included, dag_predecessors2q_rar_included)

        if num_iter > 1:
            # dependency counts for the inverse of the DAG
            dag_backward_dependencies_count = compute_transitive_closure_bitset(dag_predecessors2q_rar_included, successors2q_rar_included)
        else:
            dag_backward_dependencies_count = dag_forward_dependencies_count

        # Alternate forward/backward when num_iter>1. Keep best
        for i in range(2*(num_iter-1)+1):
            if i % 2 == 0:
                self.dag_dependencies_count = dag_forward_dependencies_count
                self.dag2q = successors2q
                self.dag_predecessors2q = dag_predecessors2q
                self.dag2q_restricted = successors2q_rar_included
                self.dag_predecessors2q_restricted = dag_predecessors2q_rar_included
                self.dag_full = successors_full
                self.dag_predecessors_full = copy.deepcopy(dag_predecessors_full) if num_iter > 1 else dag_predecessors_full
            else:
                self.dag_dependencies_count = dag_backward_dependencies_count
                self.dag2q = dag_predecessors2q
                self.dag_predecessors2q = successors2q
                self.dag2q_restricted = dag_predecessors2q_rar_included
                self.dag_predecessors2q_restricted = successors2q_rar_included
                self.dag_full = dag_predecessors_full
                self.dag_predecessors_full = copy.deepcopy(successors_full) if num_iter > 1 else successors_full

            self.init_front_layer()
            self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
            start = time()
            swap_count = self.execute_algorithm(
                heuristic_method, look_ahead_param, verbose)
            exec_time = time()-start
            if i % 2 == 0:
                if swap_count < min_swaps:
                    min_swaps = min(min_swaps, swap_count)
                    min_depth = min(min_depth, self.get_circuit_depth())
                elif swap_count == min_swaps:
                    min_depth = min(min_depth, self.get_circuit_depth())

        return min_swaps, min_depth, exec_time

    def init_mapping(self):
        """
        Time-Sensitive Multi-Start Mapping with Lookahead Greedy (TSMM-LG)

        Novel improvements over MSGCM-RLS:
        1. Time-weighted interaction scoring: exponentially higher weight for early
        circuit gates — directly prioritizes placement where routing overhead
        is unavoidable (no prior SWAPs possible before first gates).
        2. Priority-balanced greedy ordering: qubit placement priority combines
        placed-set connectivity AND 0.15x unplaced-set connectivity to prevent
        stranding high-degree qubits that are temporarily disconnected.
        3. 1-step lookahead in greedy: placement cost estimate includes the
        expected best-case cost of placing the most-connected unplaced neighbor,
        reducing myopic decisions that trap future placements.
        4. Expanded multi-start: 4x4=16 seeds vs 3x3=9 for broader landscape coverage.
        5. 30-pass local search (vs 20) for more thorough convergence.
        """
        from collections import defaultdict, deque
        import math

        # ------------------------------------------------------------------ #
        # 1. Build interaction graphs (raw count + time-weighted)              #
        # ------------------------------------------------------------------ #
        logical_qubit_set = set()
        raw_inter = defaultdict(dict)
        time_inter = defaultdict(dict)

        sorted_gates = sorted(self.access.keys())
        two_q_ordered = [(g, self.access[g]) for g in sorted_gates if len(self.access[g]) == 2]
        N2 = len(two_q_ordered)

        for idx, (gate, qubits) in enumerate(two_q_ordered):
            q1, q2 = qubits[0], qubits[1]
            logical_qubit_set.update([q1, q2])
            raw_inter[q1][q2] = raw_inter[q1].get(q2, 0) + 1
            raw_inter[q2][q1] = raw_inter[q2].get(q1, 0) + 1
            # Exponential decay: earlier 2Q gates weighted more heavily
            tw = math.exp(-3.0 * idx / max(1, N2 - 1))
            time_inter[q1][q2] = time_inter[q1].get(q2, 0.0) + tw
            time_inter[q2][q1] = time_inter[q2].get(q1, 0.0) + tw

        for gate, qubits in self.access.items():
            for q in qubits:
                logical_qubit_set.add(q)

        logical_qubits = sorted(logical_qubit_set)
        physical_qubits = sorted(self.backend.keys())

        if not logical_qubits:
            self.mapping_dict = list(range(self.num_qubits))
            self.reverse_mapping_dict = list(range(self.num_qubits))
            if self.use_isl:
                self.isl_mapping = dict_to_isl_map(self.mapping_dict)
            return

        # ------------------------------------------------------------------ #
        # 2. Graduated criticality via DP on 2Q gate DAG                      #
        # ------------------------------------------------------------------ #
        two_qubit_gates = {g: q for g, q in self.access.items() if len(q) == 2}
        qubit_criticality = defaultdict(float)
        dp_len = {}
        dp_prev_map = {}

        if two_qubit_gates:
            sorted_2q = sorted(two_qubit_gates.keys())
            last_g = {}
            dag_succ = defaultdict(set)
            dag_pred = defaultdict(set)

            for gate in sorted_2q:
                q1, q2 = two_qubit_gates[gate]
                for q in (q1, q2):
                    if q in last_g:
                        pred = last_g[q]
                        dag_succ[pred].add(gate)
                        dag_pred[gate].add(pred)
                last_g[q1] = gate
                last_g[q2] = gate

            in_deg = {g: len(dag_pred[g]) for g in sorted_2q}
            dp_len = {g: 1 for g in sorted_2q}
            dp_prev_map = {g: None for g in sorted_2q}
            q_topo = deque(g for g in sorted_2q if in_deg[g] == 0)

            while q_topo:
                node = q_topo.popleft()
                for succ in dag_succ[node]:
                    if dp_len[node] + 1 > dp_len[succ]:
                        dp_len[succ] = dp_len[node] + 1
                        dp_prev_map[succ] = node
                    in_deg[succ] -= 1
                    if in_deg[succ] == 0:
                        q_topo.append(succ)

            cp_len = max(dp_len.values()) if dp_len else 1
            threshold = max(1, cp_len * 0.82)

            for g in sorted_2q:
                if dp_len[g] >= threshold:
                    r = dp_len[g] / cp_len
                    for q in two_qubit_gates[g]:
                        qubit_criticality[q] = max(qubit_criticality[q], r)

            node = max(sorted_2q, key=lambda g: dp_len[g])
            while node is not None:
                for q in two_qubit_gates[node]:
                    qubit_criticality[q] = 1.0
                node = dp_prev_map[node]

        # ------------------------------------------------------------------ #
        # 3. Enhanced weights: time-blend + criticality bonus                  #
        #    w = [(1-T)*raw + T*time_weighted] * criticality_bonus             #
        # ------------------------------------------------------------------ #
        MAX_BONUS = 5.0
        TIME_BLEND = 0.40  # fraction of time-weighted vs raw count

        enhanced = defaultdict(dict)
        for q1 in raw_inter:
            for q2, w_raw in raw_inter[q1].items():
                c1 = qubit_criticality.get(q1, 0.0)
                c2 = qubit_criticality.get(q2, 0.0)
                bonus = 1.0 + (MAX_BONUS - 1.0) * (c1 + c2) * 0.5
                w_time = time_inter[q1].get(q2, 0.0)
                enhanced[q1][q2] = ((1 - TIME_BLEND) * w_raw + TIME_BLEND * w_time) * bonus

        # ------------------------------------------------------------------ #
        # 4. Hardware / logical seed selection                                  #
        # ------------------------------------------------------------------ #
        hw_sum_dist = {
            p: sum(
                self.distance_matrix[p][o]
                for o in physical_qubits
                if self.distance_matrix[p][o] != float('inf')
            )
            for p in physical_qubits
        }
        K_PHYS = min(4, len(physical_qubits))
        top_phys_seeds = sorted(physical_qubits, key=lambda p: hw_sum_dist[p])[:K_PHYS]

        enhanced_deg = {lq: sum(enhanced[lq].values()) for lq in logical_qubits}
        K_LQ = min(4, len(logical_qubits))
        top_lq_seeds = sorted(logical_qubits, key=lambda lq: -enhanced_deg[lq])[:K_LQ]

        # ------------------------------------------------------------------ #
        # 5. Objective function                                                 #
        # ------------------------------------------------------------------ #
        def total_cost(lq_to_phys):
            total = 0.0
            seen = set()
            for q1, q2_dict in enhanced.items():
                if q1 not in lq_to_phys:
                    continue
                for q2, w in q2_dict.items():
                    if q2 not in lq_to_phys:
                        continue
                    pair = (min(q1, q2), max(q1, q2))
                    if pair in seen:
                        continue
                    seen.add(pair)
                    d = self.distance_matrix[lq_to_phys[q1]][lq_to_phys[q2]]
                    total += w * (d if d != float('inf') else 1e9)
            return total

        # ------------------------------------------------------------------ #
        # 6. Greedy expansion with balanced ordering and 1-step lookahead      #
        # ------------------------------------------------------------------ #
        def greedy_expand(anchor_lq, anchor_phys):
            lq_to_phys = {anchor_lq: anchor_phys}
            placed_phys = {anchor_phys}
            unplaced = [lq for lq in logical_qubits if lq != anchor_lq]
            unplaced_set = set(unplaced)

            while unplaced:
                # Balanced priority: immediate connectivity + scaled future connectivity
                # Prevents stranding qubits with many unplaced high-weight neighbors
                next_lq = max(
                    unplaced,
                    key=lambda lq: (
                        sum(enhanced[lq].get(pl, 0) for pl in lq_to_phys)
                        + 0.15 * sum(enhanced[lq].get(u, 0) for u in unplaced_set if u != lq)
                    )
                )

                cands = list({
                    nb for phys in placed_phys
                    for nb in self.backend[phys] if nb not in placed_phys
                })
                if not cands:
                    cands = [p for p in physical_qubits if p not in placed_phys]
                if not cands:
                    break

                # Identify top unplaced neighbor for 1-step lookahead
                top_unplaced_nb = max(
                    (lq for lq in unplaced if lq != next_lq and enhanced[next_lq].get(lq, 0) > 0),
                    key=lambda lq: enhanced[next_lq].get(lq, 0),
                    default=None
                )

                def place_cost(phys_c):
                    # Direct cost: weighted distance to all placed qubits
                    cost = sum(
                        enhanced[next_lq].get(pl, 0) * (
                            self.distance_matrix[phys_c][pp]
                            if self.distance_matrix[phys_c][pp] != float('inf') else 1e9
                        )
                        for pl, pp in lq_to_phys.items()
                        if enhanced[next_lq].get(pl, 0) > 0
                    )

                    if top_unplaced_nb is None:
                        return cost

                    # 1-step lookahead: best placement for top unplaced neighbor
                    temp_placed = placed_phys | {phys_c}
                    nb_cands = [
                        nb for phys in temp_placed
                        for nb in self.backend[phys] if nb not in temp_placed
                    ][:12]
                    if not nb_cands:
                        nb_cands = [p for p in physical_qubits if p not in temp_placed][:12]
                    if not nb_cands:
                        return cost

                    temp_map_items = list(lq_to_phys.items()) + [(next_lq, phys_c)]
                    best_nb_cost = min(
                        sum(
                            enhanced[top_unplaced_nb].get(pl, 0) * (
                                self.distance_matrix[nc][pp]
                                if self.distance_matrix[nc][pp] != float('inf') else 1e9
                            )
                            for pl, pp in temp_map_items
                            if enhanced[top_unplaced_nb].get(pl, 0) > 0
                        )
                        for nc in nb_cands
                    )

                    return cost + 0.25 * best_nb_cost

                best_phys = min(cands, key=place_cost)
                lq_to_phys[next_lq] = best_phys
                placed_phys.add(best_phys)
                unplaced.remove(next_lq)
                unplaced_set.discard(next_lq)

            return lq_to_phys

        # ------------------------------------------------------------------ #
        # 7. Local search: pairwise swap + relocation (30 passes)              #
        # ------------------------------------------------------------------ #
        def local_search(lq_to_phys):
            lq_list = [lq for lq in logical_qubits if lq in lq_to_phys]
            occupied = set(lq_to_phys.values())
            unoccupied = [p for p in physical_qubits if p not in occupied]
            n = len(lq_list)

            for _pass in range(30):
                improved = False

                # --- Pairwise swap moves ---
                for i in range(n):
                    for j in range(i + 1, n):
                        lq1, lq2 = lq_list[i], lq_list[j]
                        p1, p2 = lq_to_phys[lq1], lq_to_phys[lq2]
                        delta = 0.0

                        for lq3, w in enhanced[lq1].items():
                            if lq3 not in lq_to_phys or lq3 == lq2:
                                continue
                            p3 = lq_to_phys[lq3]
                            d_old = self.distance_matrix[p1][p3]
                            d_new = self.distance_matrix[p2][p3]
                            delta += w * (
                                (d_new if d_new != float('inf') else 1e9) -
                                (d_old if d_old != float('inf') else 1e9)
                            )

                        for lq3, w in enhanced[lq2].items():
                            if lq3 not in lq_to_phys or lq3 == lq1:
                                continue
                            p3 = lq_to_phys[lq3]
                            d_old = self.distance_matrix[p2][p3]
                            d_new = self.distance_matrix[p1][p3]
                            delta += w * (
                                (d_new if d_new != float('inf') else 1e9) -
                                (d_old if d_old != float('inf') else 1e9)
                            )

                        if delta < -1e-9:
                            lq_to_phys[lq1], lq_to_phys[lq2] = p2, p1
                            improved = True

                # --- Relocation moves: move lq to best unoccupied slot ---
                if unoccupied:
                    for lq in lq_list:
                        p_old = lq_to_phys[lq]
                        best_delta = -1e-9
                        best_p = None

                        for p_new in unoccupied:
                            delta = 0.0
                            for lq2, w in enhanced[lq].items():
                                if lq2 not in lq_to_phys:
                                    continue
                                p2 = lq_to_phys[lq2]
                                d_old = self.distance_matrix[p_old][p2]
                                d_new = self.distance_matrix[p_new][p2]
                                delta += w * (
                                    (d_new if d_new != float('inf') else 1e9) -
                                    (d_old if d_old != float('inf') else 1e9)
                                )
                            if delta < best_delta:
                                best_delta = delta
                                best_p = p_new

                        if best_p is not None:
                            lq_to_phys[lq] = best_p
                            unoccupied.remove(best_p)
                            unoccupied.append(p_old)
                            improved = True

                if not improved:
                    break

            return lq_to_phys

        # ------------------------------------------------------------------ #
        # 8. Multi-start: 4 logical seeds x 4 physical seeds = 16 trials      #
        # ------------------------------------------------------------------ #
        best_mapping = None
        best_score = float('inf')

        for anchor_lq in top_lq_seeds:
            for anchor_phys in top_phys_seeds:
                lq_to_phys = greedy_expand(anchor_lq, anchor_phys)
                lq_to_phys = local_search(lq_to_phys)
                score = total_cost(lq_to_phys)
                if score < best_score:
                    best_score = score
                    best_mapping = dict(lq_to_phys)

        lq_to_phys = best_mapping

        # ------------------------------------------------------------------ #
        # 9. Build strict 1-to-1 bijection via in-place swap                  #
        # ------------------------------------------------------------------ #
        mapping_dict = list(range(self.num_qubits))
        reverse_mapping_dict = list(range(self.num_qubits))

        for lq, target_phys in lq_to_phys.items():
            current_phys = mapping_dict[lq]
            if current_phys == target_phys:
                continue
            displaced_lq = reverse_mapping_dict[target_phys]
            mapping_dict[lq] = target_phys
            mapping_dict[displaced_lq] = current_phys
            reverse_mapping_dict[target_phys] = lq
            reverse_mapping_dict[current_phys] = displaced_lq

        self.mapping_dict = mapping_dict
        self.reverse_mapping_dict = reverse_mapping_dict

        if self.use_isl:
            self.isl_mapping = dict_to_isl_map(self.mapping_dict)
        
        
    def init_front_layer(self):
        self.front_layer = set()
        for gate in self.dag_full:
            if len(self.dag_predecessors_full[gate]) == 0:
                self.front_layer.add(gate)

    def execute_algorithm(self, huristic_method, param, verbose):
        swap_count = 0
        total_gates = len(self.access)
        self.decay_parameter = [1 for _ in range(self.num_qubits)]

        with tqdm(total=total_gates, desc="Running Qlosure", mininterval=0.1, disable=(verbose == 0), leave=True) as pbar:
            while len(self.front_layer) > 0:

                ready_to_execute_gates = self.extract_ready_to_execute_gate_list()
                if len(ready_to_execute_gates) > 0:

                    self.update_front_layer(ready_to_execute_gates)

                    self.decay_parameter = [1 for _ in range(self.num_qubits)]
                    pbar.update(len(ready_to_execute_gates))

                else:

                    local_swap_count = self.apply_qlosure_heuristic(param)

                    swap_count += local_swap_count

        return swap_count

    def extract_ready_to_execute_gate_list(self,):
        ready_to_execute_gates_list = []

        for gate in self.front_layer:
            if self.is_gate_executable(gate):
                ready_to_execute_gates_list.append(gate)

        return ready_to_execute_gates_list

    def is_gate_executable(self, gate) -> bool:
        if len(self.access[gate]) == 1:
            q = self.access[gate][0]
            phys_q = self.mapping_dict[q]
            new_depth = self.qubit_depth.get(phys_q, 0) + 1
            self.qubit_depth[phys_q] = new_depth
            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True

        q1, q2 = self.access[gate]
        phys_q1, phys_q2 = self.mapping_dict[q1], self.mapping_dict[q2]

        if (phys_q1, phys_q2) in self.backend_connections or (phys_q2, phys_q1) in self.backend_connections:
            current_depth_q1 = self.qubit_depth.get(phys_q1, 0)
            current_depth_q2 = self.qubit_depth.get(phys_q2, 0)
            new_depth = max(current_depth_q1, current_depth_q2) + 1

            self.qubit_depth[phys_q1] = new_depth
            self.qubit_depth[phys_q2] = new_depth

            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True
        return False

    def update_front_layer(self, executable_gates):
        for gate in executable_gates:
            for successor_gate in self.dag_full[gate]:
                self.dag_predecessors_full[successor_gate].discard(gate)
                if len(self.dag_predecessors_full[successor_gate]) == 0:
                    self.front_layer.add(successor_gate)

            self.front_layer.discard(gate)
            
    def update_depth(self, q1, q2):

        current_depth_q1 = self.qubit_depth.get(q1, 0)
        current_depth_q2 = self.qubit_depth.get(q2, 0)
        new_depth = max(current_depth_q1, current_depth_q2) + 1

        self.qubit_depth[q1] = new_depth
        self.qubit_depth[q2] = new_depth

        if self.with_circuit:
            self.circuit.swap(q1, q2)

    def get_circuit_depth(self):
        return max(self.qubit_depth.values())

    def apply_qlosure_heuristic(self, param):

        logical_qubits = [q for gate in self.front_layer for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, self.extended_layer_index = create_leveled_extended_successor_set(self.front_layer, self.dag2q_restricted, self.access2q, len(physical_qubits)*param)

        candidate_swaps = generate_swap_candidates(physical_qubits, self.backend)

        heuristic_score = {}
        for swap_gate in candidate_swaps:
            self.temp_mapping_dict = swap_logical_physical_mappings(self.mapping_dict, self.reverse_mapping_dict, swap_gate)

            score = self.qlosure_poly_heuristic(swap_gate)
            heuristic_score[swap_gate] = score

        best_swap_gate = find_min_score_swap_gate(heuristic_score)

        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True)

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1
    
################################################################################################################################################################
#                                                                  Qlosure Cost Function                                                                       #
################################################################################################################################################################    
    def qlosure_poly_heuristic(self, swap_gate):
        W = 1
        front_layer_size = len(self.front_layer)
        extended_layer_size = len(self.extended_layer)

        max_decay = max(self.decay_parameter[swap_gate[0]], self.decay_parameter[swap_gate[1]])

        f_distance = 0

        for g in self.front_layer:
            q1, q2 = self.access2q[g]
            Q1, Q2 = self.temp_mapping_dict[q1], self.temp_mapping_dict[q2]
            deps = self.dag_dependencies_count[g]

            f_distance += (deps+1) * self.distance_matrix[Q1][Q2]

        e_distance = 0
        for g in self.extended_layer:
            q1, q2 = self.access2q[g]
            Q1, Q2 = self.temp_mapping_dict[q1], self.temp_mapping_dict[q2]
            layer_factor = self.extended_layer_index.get(g, 0) + 1

            deps = self.dag_dependencies_count[g]
            e_distance += (deps+1) * \
                self.distance_matrix[Q1][Q2] * 1/layer_factor

        H = max_decay * (f_distance / front_layer_size + W *
                        ((e_distance / extended_layer_size) if extended_layer_size else 0))

        return H
################################################################################################################################################################
