import random
import copy
from time import time
from tqdm import tqdm
import islpy as isl
from src.mapping.heuristic import *
from src.mapping.mapping import *
from src.utils.circuit_utils import *
from src.utils.isl_data_loader import *
from src.graph.graph import *
import math

class Qlosure():
    def __init__(self, edges, data, use_isl=False, with_circuit=True) -> None:

        # Normalize edges as tuple pairs for O(1) checks
        self.backend_connections = set(tuple(edge) for edge in edges)
        # Build backend graph as adjacency list
        self.backend = build_backend_graph(edges)
        self.use_isl = use_isl
        self.with_circuit = with_circuit
        # Program meta data generated by qrane
        self.data = data
        # Precompute distances over the hardware graph
        self.distance_matrix = compute_distance_matrix(self.backend)
        # Number of physical qubits
        self.num_qubits = len(self.distance_matrix) + 1
        # A dictionary mapping each gate to a list of the qubits it acts upon
        self.access, self.write_dict = self.data["read"], self.data["write"]
        self.macro_gates = self.data.get("macro_gates", {})
        self.access2q = None
        self.decay_parameter = [1 for _ in range(self.num_qubits)]
        self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
        self.reset = 5
        self.isl_mapping = None
        self.mapping_dict = None
        self.reverse_mapping_dict = None
        self.front_layer = None
        self.extended_layer = None

        if with_circuit:
            self.circuit = QuantumCircuit(self.num_qubits - 1)
            self.original_circuit = QuantumCircuit.from_qasm_str(data.get("qasm_code", ""))

        self.results = {}
        self.instruction_times = defaultdict(int)

    def run(self, heuristic_method="Qlosure", enforce_read_after_read=True, transitive_reduction=True, initial_mapping_method="trivial", dag_mode="default", num_iter=1, look_ahead_param=5, verbose=0):
        """
        Execute the mapping/scheduling loop and return (min_swaps, min_depth, exec_time).
        The method alternates between forward and backward DAG passes when
        num_iter > 1, keeping the best result across passes.
        """

        # Initialize the logical->physical mapping
        self.init_mapping()

        self.results = {}
        min_swaps = float('inf')
        min_depth = float('inf')

        # Build DAGs and a 2-qubit-only view of access for heuristics
        successors2q, dag_predecessors2q, successors_full, dag_predecessors_full, self.access2q = generate_dag(self.access, self.write_dict, self.num_qubits, enforce_read_after_read, transitive_reduction)

        if not enforce_read_after_read and dag_mode == "hybrid":
            successors2q_rar_included, dag_predecessors2q_rar_included, _, _, _ = generate_dag(self.access, self.write_dict, self.num_qubits, enforce_read_after_read=True, transitive_reduction=transitive_reduction)
        else:
            successors2q_rar_included = successors2q
            dag_predecessors2q_rar_included = dag_predecessors2q

        # Precompute dependency counts using our own implementation of the transitive closure
        dag_forward_dependencies_count = compute_transitive_closure_bitset(successors2q_rar_included, dag_predecessors2q_rar_included)

        if num_iter > 1:
            # dependency counts for the inverse of the DAG
            dag_backward_dependencies_count = compute_transitive_closure_bitset(dag_predecessors2q_rar_included, successors2q_rar_included)
        else:
            dag_backward_dependencies_count = dag_forward_dependencies_count

        # Alternate forward/backward when num_iter>1. Keep best
        for i in range(2*(num_iter-1)+1):
            if i % 2 == 0:
                self.dag_dependencies_count = dag_forward_dependencies_count
                self.dag2q = successors2q
                self.dag_predecessors2q = dag_predecessors2q
                self.dag2q_restricted = successors2q_rar_included
                self.dag_predecessors2q_restricted = dag_predecessors2q_rar_included
                self.dag_full = successors_full
                self.dag_predecessors_full = copy.deepcopy(dag_predecessors_full) if num_iter > 1 else dag_predecessors_full
            else:
                self.dag_dependencies_count = dag_backward_dependencies_count
                self.dag2q = dag_predecessors2q
                self.dag_predecessors2q = successors2q
                self.dag2q_restricted = dag_predecessors2q_rar_included
                self.dag_predecessors2q_restricted = successors2q_rar_included
                self.dag_full = dag_predecessors_full
                self.dag_predecessors_full = copy.deepcopy(successors_full) if num_iter > 1 else successors_full

            self.init_front_layer()
            self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
            start = time()
            swap_count = self.execute_algorithm(
                heuristic_method, look_ahead_param, verbose)
            exec_time = time()-start
            if i % 2 == 0:
                if swap_count < min_swaps:
                    min_swaps = min(min_swaps, swap_count)
                    min_depth = min(min_depth, self.get_circuit_depth())
                elif swap_count == min_swaps:
                    min_depth = min(min_depth, self.get_circuit_depth())

        return min_swaps, min_depth, exec_time

    def init_mapping(self):
        """Gravity-Well Placement: physics-based force simulation for initial mapping."""
        import numpy as np
        from scipy.optimize import linear_sum_assignment
        from collections import defaultdict

        # ── 1. Collect logical qubits and build interaction graph ────────────
        logical_qubits = sorted({q for qubits in self.access.values() for q in qubits})
        num_logical = len(logical_qubits)

        if num_logical == 0:
            self.mapping_dict = {}
            self.reverse_mapping_dict = {}
            return

        log_idx = {q: i for i, q in enumerate(logical_qubits)}

        # Interaction weights between logical qubit pairs and per-qubit mass
        interaction_weights = defaultdict(float)
        qubit_mass = defaultdict(float)
        for gate, qubits in self.access.items():
            if len(qubits) == 2:
                q1, q2 = qubits
                edge = (min(q1, q2), max(q1, q2))
                interaction_weights[edge] += 1.0
                qubit_mass[q1] += 1.0
                qubit_mass[q2] += 1.0

        # ── 2. Physical qubits and hardware centrality ───────────────────────
        phys_qubits = sorted(self.backend.keys())
        num_phys = len(phys_qubits)

        # Closeness centrality from distance_matrix
        centrality = np.zeros(num_phys)
        for i, p in enumerate(phys_qubits):
            total_dist = sum(
                self.distance_matrix[p][q] for q in phys_qubits
                if q != p and self.distance_matrix[p][q] < float('inf')
            )
            centrality[i] = (num_phys - 1) / total_dist if total_dist > 0 else 0.0

        # ── 3. Spectral embedding of hardware graph (MDS on distance matrix) ─
        # Classical MDS: double-center the squared distance matrix, eigendecompose
        k = 2
        D = np.zeros((num_phys, num_phys))
        for i, p1 in enumerate(phys_qubits):
            for j, p2 in enumerate(phys_qubits):
                d = self.distance_matrix[p1][p2]
                D[i, j] = d if d < float('inf') else 0.0

        D_sq = D ** 2
        H_mat = np.eye(num_phys) - np.ones((num_phys, num_phys)) / num_phys
        B = -0.5 * H_mat @ D_sq @ H_mat

        try:
            eigenvalues, eigenvectors = np.linalg.eigh(B)
            idx_sorted = np.argsort(eigenvalues)[::-1][:k]
            phys_coords = eigenvectors[:, idx_sorted] * np.sqrt(
                np.maximum(eigenvalues[idx_sorted], 0.0)
            )
        except np.linalg.LinAlgError:
            phys_coords = np.random.randn(num_phys, k) * 0.1

        # ── 4. Initialize logical qubit positions ────────────────────────────
        # Heavy logical qubits start near high-centrality physical positions;
        # all positions receive random perturbation to break symmetry.
        c_sum = centrality.sum()
        if c_sum > 0:
            centrality_weighted_center = (centrality[:, None] * phys_coords).sum(axis=0) / c_sum
        else:
            centrality_weighted_center = phys_coords.mean(axis=0)

        spread = max(phys_coords.std(), 1e-3)
        positions = np.zeros((num_logical, k))
        rng = np.random.default_rng(42)
        for i, q in enumerate(logical_qubits):
            mass = qubit_mass.get(q, 0.0) + 1.0
            # Heavier qubits start closer to centrality-weighted center
            alpha = min(mass / (mass + 5.0), 0.9)
            positions[i] = (
                alpha * centrality_weighted_center
                + (1.0 - alpha) * phys_coords[rng.integers(num_phys)]
                + rng.normal(0, spread * 0.3, size=k)
            )

        # ── 5. Damped force simulation ───────────────────────────────────────
        dt = 0.05
        damping = 0.85
        velocities = np.zeros((num_logical, k))
        max_iters = 150

        # Precompute interaction list for efficiency
        interactions = [
            (log_idx[q1], log_idx[q2], w)
            for (q1, q2), w in interaction_weights.items()
        ]
        masses = np.array([qubit_mass.get(q, 0.0) + 1.0 for q in logical_qubits])

        for iteration in range(max_iters):
            forces = np.zeros((num_logical, k))

            # (a) Attractive forces between interacting logical qubit pairs
            #     Spring-like: proportional to gate weight, capped to prevent blowup
            for i, j, w in interactions:
                diff = positions[j] - positions[i]
                dist = np.linalg.norm(diff) + 1e-10
                f_attract = w * diff / dist * min(dist, 2.0 * spread)
                forces[i] += f_attract
                forces[j] -= f_attract

            # (b) Repulsive forces between all logical qubit pairs (Coulomb-like)
            #     Prevents overlap: inversely proportional to distance squared
            for i in range(num_logical):
                for j in range(i + 1, num_logical):
                    diff = positions[j] - positions[i]
                    dist_sq = np.dot(diff, diff) + 1e-10
                    dist = np.sqrt(dist_sq)
                    repulsion = spread * diff / (dist_sq * dist) * 0.5
                    forces[i] -= repulsion
                    forces[j] += repulsion

            # (c) Gravitational pull toward high-centrality hardware nodes
            #     Scales with logical qubit mass × physical centrality / distance²
            for i in range(num_logical):
                grav = np.zeros(k)
                m_i = masses[i]
                for j_p in range(num_phys):
                    diff = phys_coords[j_p] - positions[i]
                    dist = np.linalg.norm(diff) + 1e-10
                    grav += centrality[j_p] * m_i * diff / (dist ** 2)
                forces[i] += grav * 0.02

            # Update velocities (damped) and positions
            velocities = damping * (velocities + forces * dt)
            positions += velocities * dt

            # Early convergence check
            if np.max(np.abs(velocities)) < 1e-7:
                break

        # ── 6. Snap to physical qubits via Hungarian algorithm ───────────────
        # Cost = Euclidean distance between converged logical positions and
        # physical qubit coordinates in the MDS embedding space.
        # linear_sum_assignment guarantees a strict 1-to-1 matching.
        cost = np.zeros((num_logical, num_phys))
        for i in range(num_logical):
            for j in range(num_phys):
                cost[i, j] = np.linalg.norm(positions[i] - phys_coords[j])

        row_ind, col_ind = linear_sum_assignment(cost)

        self.mapping_dict = {}
        self.reverse_mapping_dict = {}
        for li, pi in zip(row_ind, col_ind):
            lq = logical_qubits[li]
            pq = phys_qubits[pi]
            self.mapping_dict[lq] = pq
            self.reverse_mapping_dict[pq] = lq

        if self.use_isl:
            self.isl_mapping = dict_to_isl_map(self.mapping_dict)
        
    def init_front_layer(self):
        self.front_layer = set()
        for gate in self.dag_full:
            if len(self.dag_predecessors_full[gate]) == 0:
                self.front_layer.add(gate)

    def execute_algorithm(self, huristic_method, param, verbose):
        swap_count = 0
        total_gates = len(self.access)
        self.decay_parameter = [1 for _ in range(self.num_qubits)]

        with tqdm(total=total_gates, desc="Running Qlosure", mininterval=0.1, disable=(verbose == 0), leave=True) as pbar:
            while len(self.front_layer) > 0:

                ready_to_execute_gates = self.extract_ready_to_execute_gate_list()
                if len(ready_to_execute_gates) > 0:

                    self.update_front_layer(ready_to_execute_gates)

                    self.decay_parameter = [1 for _ in range(self.num_qubits)]
                    pbar.update(len(ready_to_execute_gates))

                else:

                    local_swap_count = self.apply_qlosure_heuristic(param)

                    swap_count += local_swap_count

        return swap_count

    def extract_ready_to_execute_gate_list(self,):
        ready_to_execute_gates_list = []

        for gate in self.front_layer:
            if self.is_gate_executable(gate):
                ready_to_execute_gates_list.append(gate)

        return ready_to_execute_gates_list

    def is_gate_executable(self, gate) -> bool:
        if len(self.access[gate]) == 1:
            q = self.access[gate][0]
            phys_q = self.mapping_dict[q]
            new_depth = self.qubit_depth.get(phys_q, 0) + 1
            self.qubit_depth[phys_q] = new_depth
            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True

        q1, q2 = self.access[gate]
        phys_q1, phys_q2 = self.mapping_dict[q1], self.mapping_dict[q2]

        if (phys_q1, phys_q2) in self.backend_connections or (phys_q2, phys_q1) in self.backend_connections:
            current_depth_q1 = self.qubit_depth.get(phys_q1, 0)
            current_depth_q2 = self.qubit_depth.get(phys_q2, 0)
            new_depth = max(current_depth_q1, current_depth_q2) + 1

            self.qubit_depth[phys_q1] = new_depth
            self.qubit_depth[phys_q2] = new_depth

            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True
        return False

    def update_front_layer(self, executable_gates):
        for gate in executable_gates:
            for successor_gate in self.dag_full[gate]:
                self.dag_predecessors_full[successor_gate].discard(gate)
                if len(self.dag_predecessors_full[successor_gate]) == 0:
                    self.front_layer.add(successor_gate)

            self.front_layer.discard(gate)
            
    def update_depth(self, q1, q2):

        current_depth_q1 = self.qubit_depth.get(q1, 0)
        current_depth_q2 = self.qubit_depth.get(q2, 0)
        new_depth = max(current_depth_q1, current_depth_q2) + 1

        self.qubit_depth[q1] = new_depth
        self.qubit_depth[q2] = new_depth

        if self.with_circuit:
            self.circuit.swap(q1, q2)

    def get_circuit_depth(self):
        return max(self.qubit_depth.values())

    def apply_qlosure_heuristic(self, param):

        logical_qubits = [q for gate in self.front_layer for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, self.extended_layer_index = create_leveled_extended_successor_set(self.front_layer, self.dag2q_restricted, self.access2q, len(physical_qubits)*param)

        candidate_swaps = generate_swap_candidates(physical_qubits, self.backend)

        heuristic_score = {}
        for swap_gate in candidate_swaps:
            self.temp_mapping_dict = swap_logical_physical_mappings(self.mapping_dict, self.reverse_mapping_dict, swap_gate)

            score = self.qlosure_poly_heuristic(swap_gate)
            heuristic_score[swap_gate] = score

        best_swap_gate = find_min_score_swap_gate(heuristic_score)

        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True)

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1
    
################################################################################################################################################################
#                                                                  Qlosure Cost Function                                                                       #
################################################################################################################################################################    
    def qlosure_poly_heuristic(self, swap_gate):
        W = 1
        front_layer_size = len(self.front_layer)
        extended_layer_size = len(self.extended_layer)

        max_decay = max(self.decay_parameter[swap_gate[0]], self.decay_parameter[swap_gate[1]])

        f_distance = 0

        for g in self.front_layer:
            q1, q2 = self.access2q[g]
            Q1, Q2 = self.temp_mapping_dict[q1], self.temp_mapping_dict[q2]
            deps = self.dag_dependencies_count[g]

            f_distance += (deps+1) * self.distance_matrix[Q1][Q2]

        e_distance = 0
        for g in self.extended_layer:
            q1, q2 = self.access2q[g]
            Q1, Q2 = self.temp_mapping_dict[q1], self.temp_mapping_dict[q2]
            layer_factor = self.extended_layer_index.get(g, 0) + 1

            deps = self.dag_dependencies_count[g]
            e_distance += (deps+1) * \
                self.distance_matrix[Q1][Q2] * 1/layer_factor

        H = max_decay * (f_distance / front_layer_size + W *
                        ((e_distance / extended_layer_size) if extended_layer_size else 0))

        return H
################################################################################################################################################################
