import random
import copy
from collections import defaultdict
from time import time

from tqdm import tqdm
import islpy as isl

from src.mapping.heuristic import *
from src.mapping.mapping import *

from src.utils.circuit_utils import *
from src.utils.isl_data_loader import *
from src.utils.isl_to_python import *
from src.utils.python_to_isl import *

from src.graph.graph import *


def build_physical_centrality_scores(distance_matrix):
    """Centrality per physical qubit: ``1 / sum_of_distances`` to every
    reachable qubit (higher = more central). ``distance_matrix`` is the
    hardware shortest-path matrix, so this is keyed by physical-qubit id
    over ``range(len(distance_matrix))``. Returns dict[int, float]."""
    centrality = {}
    for p, row in enumerate(distance_matrix):
        total = 0.0
        for d in row:
            if d != float('inf'):
                total += d
        centrality[p] = (1.0 / total) if total > 0 else 0.0
    return centrality


def build_qubit_interaction_graph(access):
    """Undirected weighted adjacency over LOGICAL qubits; the weight is the
    number of 2-qubit gates between the pair. Access as ``qig[q1][q2]``
    (returns 0 if the pair never interacts)."""
    qig = defaultdict(lambda: defaultdict(int))
    for qubits in access.values():
        if len(qubits) == 2 and qubits[0] != qubits[1]:
            a, b = qubits[0], qubits[1]
            qig[a][b] += 1
            qig[b][a] += 1
    return qig


def build_temporal_interaction_graph(access, decay_factor=0.95):
    """Same shape as the QIG, but each 2-qubit gate contributes
    ``decay_factor ** index`` where ``index`` is the gate's rank in schedule
    order (earliest = 0). EARLIER gates therefore dominate the weight.
    ``access`` keys are schedule times, so we rank by sorted key."""
    tig = defaultdict(lambda: defaultdict(float))
    for index, time_key in enumerate(sorted(access.keys())):
        qubits = access[time_key]
        if len(qubits) == 2 and qubits[0] != qubits[1]:
            a, b = qubits[0], qubits[1]
            w = decay_factor ** index
            tig[a][b] += w
            tig[b][a] += w
    return tig


def build_logical_activity_scores(qubit_interaction_graph):
    """Per-logical-qubit total interaction weight (sum of its QIG row), a
    gate-frequency proxy. Returns defaultdict[int, int]."""
    activity = defaultdict(int)
    for q, neighbors in qubit_interaction_graph.items():
        activity[q] = sum(neighbors.values())
    return activity


class Qlosure():
    def __init__(self, edges, data, use_isl=False, with_circuit=True) -> None:

        # Normalize edges as tuple pairs for O(1) checks
        self.backend_connections = set(tuple(edge) for edge in edges)
        # Build backend graph as adjacency list
        self.backend = build_backend_graph(edges)

        self.use_isl = use_isl
        self.with_circuit = with_circuit

        # Program meta data generated by qrane
        self.data = data

        # Precompute distances over the hardware graph
        self.distance_matrix = compute_distance_matrix(self.backend)

        self.num_qubits = len(self.distance_matrix) + 1

        self.access, self.write_dict = self.data["read"], self.data["write"]
        self.macro_gates = self.data.get("macro_gates", {})
        self.access2q = None

        # Read-only structural signals consumed by init_mapping heuristics.
        # physical_centrality is keyed by physical qubit over the distance
        # matrix; the interaction graphs / activity are over logical qubits.
        self.physical_centrality = build_physical_centrality_scores(
            self.distance_matrix)
        self.qubit_interaction_graph = build_qubit_interaction_graph(
            self.access)
        self.temporal_interaction_graph = build_temporal_interaction_graph(
            self.access)
        self.logical_activity = build_logical_activity_scores(
            self.qubit_interaction_graph)

        self.decay_parameter = [1 for _ in range(self.num_qubits)]
        self.qubit_depth = {q: 0 for q in range(self.num_qubits)}

        self.reset = 5
        self.isl_mapping = None
        self.mapping_dict = None
        self.reverse_mapping_dict = None
        self.front_layer = None
        self.extended_layer = None

        if with_circuit:
            self.circuit = QuantumCircuit(self.num_qubits - 1)
            self.original_circuit = QuantumCircuit.from_qasm_str(
                data.get("qasm_code", ""))

        self.results = {}
        self.instruction_times = defaultdict(int)
        self.init_time = 0.0

    def run(self, heuristic_method="qlosure", enforce_read_after_read=True, transitive_reduction=True, initial_mapping_method="cblc", dag_mode="default", num_iter=6, look_ahead_param=5, verbose=0):


        self.results = {}

        # Build DAGs and a 2-qubit-only view of access for heuristics
        successors2q, dag_predecessors2q, successors_full, dag_predecessors_full, self.access2q = generate_dag(
            self.access, self.write_dict, self.num_qubits, enforce_read_after_read, transitive_reduction)

        if not enforce_read_after_read and dag_mode == "hybrid":
            successors2q_rar_included, dag_predecessors2q_rar_included, _, _, _ = generate_dag(
                self.access, self.write_dict, self.num_qubits, enforce_read_after_read=True, transitive_reduction=transitive_reduction)
        else:
            successors2q_rar_included = successors2q
            dag_predecessors2q_rar_included = dag_predecessors2q

        # Precompute dependency counts using our own implementation of the transitive closure
        dag_forward_dependencies_count = compute_transitive_closure_bitset(
            successors2q_rar_included, dag_predecessors2q_rar_included)

        if num_iter > 1:
            # dependency counts for the inverse of the DAG
            dag_backward_dependencies_count = compute_transitive_closure_bitset(
                dag_predecessors2q_rar_included, successors2q_rar_included)
        else:
            dag_backward_dependencies_count = dag_forward_dependencies_count

        init_start = time()
        self.init_mapping(method=initial_mapping_method)
        self.init_time = time() - init_start

        min_swaps = float('inf')
        min_depth = float('inf')
        exec_time = 0.0
        self.decay_parameter = [1 for _ in range(self.num_qubits)]

        start = time()
        for i in range(2 * (num_iter - 1) + 1):
            if i % 2 == 0:
                self.dag_dependencies_count = dag_forward_dependencies_count
                self.dag2q = successors2q
                self.dag_predecessors2q = dag_predecessors2q
                self.dag2q_restricted = successors2q_rar_included
                self.dag_predecessors2q_restricted = dag_predecessors2q_rar_included
                self.dag_full = successors_full
                self.dag_predecessors_full = copy.deepcopy(
                    dag_predecessors_full)
            else:
                self.dag_dependencies_count = dag_backward_dependencies_count
                self.dag2q = dag_predecessors2q
                self.dag_predecessors2q = successors2q
                self.dag2q_restricted = dag_predecessors2q_rar_included
                self.dag_predecessors2q_restricted = successors2q_rar_included
                self.dag_full = dag_predecessors_full
                self.dag_predecessors_full = copy.deepcopy(
                    successors_full)

            self.init_front_layer()
            self.qubit_depth = {q: 0 for q in range(self.num_qubits)}
            swap_count = self.execute_algorithm(
                heuristic_method, look_ahead_param, verbose)
            if i % 2 == 0:
                if swap_count < min_swaps:
                    min_swaps = swap_count
                    min_depth = self.get_circuit_depth()
                elif swap_count == min_swaps:
                    min_depth = min(min_depth, self.get_circuit_depth())
        exec_time = time() - start

        return min_swaps, min_depth, exec_time

    def init_mapping(self, method="cblc"):
        if method == "random":
            self.mapping_dict, self.reverse_mapping_dict = generate_random_initial_mapping(
                self.num_qubits)
        elif method == "trivial":
            self.mapping_dict, self.reverse_mapping_dict = generate_trivial_initial_mapping(
                self.num_qubits)
        elif method == "sabre":
            self.mapping_dict, self.reverse_mapping_dict = generate_sabre_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits)
        elif method == "qmap":
            self.mapping_dict, self.reverse_mapping_dict = generate_qmap_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits)
        elif method == "cirq":
            self.mapping_dict, self.reverse_mapping_dict = generate_cirq_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits)
        elif method == "pytket":
            self.mapping_dict, self.reverse_mapping_dict = generate_pytket_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits)
        elif method == "gem":
            self.mapping_dict, self.reverse_mapping_dict = generate_gem_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits,
                self.access, self.distance_matrix, self.backend)
            self._gem_portfolio_refine()
        elif method == "vex":
            self.mapping_dict, self.reverse_mapping_dict = generate_vex_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits,
                self.access, self.distance_matrix, self.backend)
        elif method == "cblc":
            self.mapping_dict, self.reverse_mapping_dict = generate_cblc_initial_mapping(
                self.data["qasm_code"], self.backend_connections, self.num_qubits,
                self.access, self.distance_matrix, self.backend)
        else:
            raise ValueError(
                f"Unknown mapping initialization method: {method!r}. "
                f"Supported: 'cblc', 'sabre', 'trivial', 'random'."
            )

        if self.use_isl:
            self.isl_mapping = dict_to_isl_map(self.mapping_dict)

    def _gem_portfolio_refine(self):
        """Ring-structured persistent circuits (QUEKO-class) on devices
        where their rings cannot embed flat: evaluate a small fixed
        portfolio of structurally-motivated mappings — the GEM result
        (influence-decay cluster), two lane-carousel placements, a
        raw-count cluster and a breathing cluster — by routing the
        first 60% of the gate list once per candidate, and keep the
        best. The portfolio is only built when the two-ring signature
        is present and the GEM mapping is not already an exact
        embedding, so all other circuit classes are untouched.
        """
        # already a zero-SWAP embedding? keep it.
        all_adj = True
        for qs in self.access.values():
            if len(qs) == 2 and qs[0] != qs[1]:
                p1, p2 = self.mapping_dict[qs[0]], self.mapping_dict[qs[1]]
                if (p1, p2) not in self.backend_connections and \
                        (p2, p1) not in self.backend_connections:
                    all_adj = False
                    break
        if all_adj:
            return

        carousels = generate_carousel_candidates(
            self.access, self.distance_matrix, self.backend,
            self.num_qubits)
        mesh = (not carousels and is_mesh_regime(
            self.access, self.backend, len(self.distance_matrix)))
        if not carousels and not mesh:
            return

        candidates = [list(self.mapping_dict)] + carousels
        if mesh:
            # lean duel for large meshes: the spectral co-embedding
            # against the GEM cluster; anything more blows the
            # per-circuit time budget at this register size.
            m = generate_spectral_descent_mapping(
                self.access, self.distance_matrix, self.backend,
                self.num_qubits)
            if m is not None:
                candidates.append(m)
        if not mesh:
            raws = generate_cluster_variant_mapping(
                self.access, self.distance_matrix, self.backend,
                self.num_qubits, mode='raw', top2=True)
            if raws:
                candidates.extend(raws)
            m = generate_cluster_variant_mapping(
                self.access, self.distance_matrix, self.backend,
                self.num_qubits, mode='decay', breathe=True)
            if m is not None:
                candidates.append(m)
            m = generate_tree_embed_mapping(
                self.access, self.distance_matrix, self.backend,
                self.num_qubits)
            if m is not None:
                candidates.append(m)
            try:
                m, _ = generate_vex_initial_mapping(
                    self.data.get("qasm_code", ""),
                    self.backend_connections,
                    self.num_qubits, self.access, self.distance_matrix,
                    self.backend)
                candidates.append(m)
            except Exception:
                pass


        # each candidate is evaluated on a fixed routing budget of
        # ~1900 2q gates: exact selection for short circuits, a long
        # prefix for deep ones. The budget is a runtime guard (keeps
        # the whole portfolio within the per-circuit time limit), not
        # a quality parameter.
        keys = sorted(self.access.keys())
        n2q = sum(1 for k in keys
                  if len(self.access[k]) == 2
                  and self.access[k][0] != self.access[k][1])
        budget = 800.0 if mesh else 1900.0
        frac = min(1.0, budget / max(n2q, 1))
        cut = keys[:max(1, int(len(keys) * frac))]
        sub = {'read': {k: self.access[k] for k in cut},
               'write': {k: self.write_dict[k] for k in cut
                         if k in self.write_dict},
               'qasm_code': ''}
        edges = list(self.backend_connections)
        best = None
        for m in candidates:
            try:
                clone = Qlosure(edges, sub, with_circuit=False)
                rev = [-1] * clone.num_qubits
                for l, p in enumerate(m):
                    if 0 <= p < len(rev):
                        rev[p] = l

                def im(zelf, method="fixed", _m=m, _r=rev):
                    zelf.mapping_dict = list(_m)
                    zelf.reverse_mapping_dict = list(_r)
                clone.init_mapping = im.__get__(clone)
                if best is not None:
                    clone.swap_abort_threshold = best[1]
                sw, _, _ = clone.run(num_iter=1)
            except Exception:
                continue
            if best is None or sw < best[1]:
                best = (m, sw)
        if best is not None:
            self.mapping_dict = list(best[0])
            rev = [-1] * self.num_qubits
            for l, p in enumerate(self.mapping_dict):
                if 0 <= p < len(rev):
                    rev[p] = l
            self.reverse_mapping_dict = rev

    def init_front_layer(self):
        self.front_layer = set()
        for gate in self.dag_full:
            if len(self.dag_predecessors_full[gate]) == 0:
                self.front_layer.add(gate)

    def execute_algorithm(self, huristic_method, param, verbose):
        swap_count = 0
        total_gates = len(self.access)
        abort_at = getattr(self, 'swap_abort_threshold', None)
        self.decay_parameter = [1 for _ in range(self.num_qubits)]

        with tqdm(total=total_gates, desc="Running Qlosure", mininterval=0.1, disable=(verbose == 0), leave=True) as pbar:
            while len(self.front_layer) > 0:
                if abort_at is not None and swap_count > abort_at:
                    return swap_count

                ready_to_execute_gates = self.extract_ready_to_execute_gate_list()
                if len(ready_to_execute_gates) > 0:

                    self.update_front_layer(
                        ready_to_execute_gates)

                    self.decay_parameter = [1 for _ in range(self.num_qubits)]
                    pbar.update(len(ready_to_execute_gates))

                else:

                    local_swap_count = self.apply_heuristic(
                        huristic_method, param, verbose=verbose)

                    swap_count += local_swap_count

        return swap_count

    def extract_ready_to_execute_gate_list(self,):
        ready_to_execute_gates_list = []

        for gate in self.front_layer:
            if self.is_gate_executable(gate):
                ready_to_execute_gates_list.append(gate)

        return ready_to_execute_gates_list

    def is_gate_executable(self, gate) -> bool:
        if len(self.access[gate]) == 1:
            q = self.access[gate][0]
            phys_q = self.mapping_dict[q]
            new_depth = self.qubit_depth.get(phys_q, 0) + 1
            self.qubit_depth[phys_q] = new_depth
            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True

        q1, q2 = self.access[gate]
        phys_q1, phys_q2 = self.mapping_dict[q1], self.mapping_dict[q2]

        if (phys_q1, phys_q2) in self.backend_connections or (phys_q2, phys_q1) in self.backend_connections:
            current_depth_q1 = self.qubit_depth.get(phys_q1, 0)
            current_depth_q2 = self.qubit_depth.get(phys_q2, 0)
            new_depth = max(current_depth_q1, current_depth_q2) + 1

            self.qubit_depth[phys_q1] = new_depth
            self.qubit_depth[phys_q2] = new_depth

            if self.with_circuit:
                replay_gate_at(self.original_circuit, gate, self.circuit, self.mapping_dict)

            return True
        return False

    def update_front_layer(self, executable_gates):
        for gate in executable_gates:
            for successor_gate in self.dag_full[gate]:
                self.dag_predecessors_full[successor_gate].discard(gate)
                if len(self.dag_predecessors_full[successor_gate]) == 0:
                    self.front_layer.add(successor_gate)

            self.front_layer.discard(gate)

    def apply_heuristic(self, huristic_method, param, verbose=0):
        if huristic_method not in ["qlosure", "layer_adjusted", "distance_only"]:
            raise ValueError(
                f"Invalid heuristic method provided {huristic_method}. ")

        if huristic_method == "qlosure":
            return self._apply_qlosure_score_heuristic(param)

        if huristic_method == "layer_adjusted":
            return self._apply_layered_qlosure_heuristic(param)

        if huristic_method == "distance_only":
            return self._apply_distance_qlosure_heuristic()

    def _apply_qlosure_score_heuristic(self, param):

        logical_qubits = [
            q for gate in self.front_layer for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, extended_layer_index = create_leveled_extended_successor_set(
            self.front_layer, self.dag2q_restricted, self.access2q, len(
                physical_qubits)*param
        )

        candidate_swaps = generate_swap_candidates(
            physical_qubits, self.backend)

        heuristic_score = {}
        for swap_gate in candidate_swaps:
            temp_mapping_dict = swap_logical_physical_mappings(
                self.mapping_dict, self.reverse_mapping_dict, swap_gate
            )

            score = qlosure_poly_heuristic(self.front_layer, self.extended_layer, temp_mapping_dict,
                                           self.distance_matrix, self.access2q, self.decay_parameter, self.dag_dependencies_count, extended_layer_index, swap_gate)
            heuristic_score[swap_gate] = score

        best_swap_gate = find_min_score_swap_gate(heuristic_score)

        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(
                self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(
            self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True
        )

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1

    def _apply_distance_qlosure_heuristic(self):
        # print("dag : ",self.dag_dependencies_count)
        # print("distance matrix : ",self.distance_matrix)
        logical_qubits = [
            q for gate in self.front_layer for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, extended_layer_index = create_leveled_extended_successor_set(
            self.front_layer, self.dag2q_restricted, self.access2q, 10
        )

        candidate_swaps = generate_swap_candidates(
            physical_qubits, self.backend)
        # print("swaps candidates", candidate_swaps)
        heuristic_score = {}
        for swap_gate in candidate_swaps:
            temp_mapping_dict = swap_logical_physical_mappings(
                self.mapping_dict, self.reverse_mapping_dict, swap_gate
            )
            # print("for swap gate", swap_gate)
            score = distance_only_poly_heuristic(self.front_layer, self.extended_layer, temp_mapping_dict,
                                                 self.distance_matrix, self.access2q, self.decay_parameter, self.dag_dependencies_count, extended_layer_index, swap_gate)
            heuristic_score[swap_gate] = score

            # print("score", score)

        best_swap_gate = find_min_score_swap_gate(heuristic_score)
        # print("best swap gate", best_swap_gate)
        # print("------------------")
        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(
                self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(
            self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True
        )

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1

    def _apply_layered_qlosure_heuristic(self, param):

        logical_qubits = [
            q for gate in self.front_layer for q in self.access2q[gate]]
        physical_qubits = set(self.mapping_dict[q] for q in logical_qubits)

        self.extended_layer, extended_layer_index = create_leveled_extended_successor_set(
            self.front_layer, self.dag2q_restricted, self.access2q, 10
        )

        candidate_swaps = generate_swap_candidates(
            physical_qubits, self.backend)

        heuristic_score = {}
        for swap_gate in candidate_swaps:
            temp_mapping_dict = swap_logical_physical_mappings(
                self.mapping_dict, self.reverse_mapping_dict, swap_gate
            )
            score = layered_poly_qlosure_heuristic(self.front_layer, self.extended_layer, temp_mapping_dict,
                                                   self.distance_matrix, self.access2q, self.decay_parameter, self.dag_dependencies_count, extended_layer_index, swap_gate)
            heuristic_score[swap_gate] = score

        best_swap_gate = find_min_score_swap_gate(heuristic_score)

        if self.use_isl:
            self.isl_mapping = swap_logical_physical_isl_mapping(
                self.isl_mapping, best_swap_gate)

        swap_logical_physical_mappings(
            self.mapping_dict, self.reverse_mapping_dict, best_swap_gate, inplace=True
        )

        self.decay_parameter[best_swap_gate[0]] += 0.001
        self.decay_parameter[best_swap_gate[1]] += 0.001

        self.update_depth(best_swap_gate[0], best_swap_gate[1])

        return 1

    def update_depth(self, q1, q2):

        current_depth_q1 = self.qubit_depth.get(q1, 0)
        current_depth_q2 = self.qubit_depth.get(q2, 0)
        new_depth = max(current_depth_q1, current_depth_q2) + 1

        self.qubit_depth[q1] = new_depth
        self.qubit_depth[q2] = new_depth

        if self.with_circuit:
            self.circuit.swap(q1, q2)

    def get_circuit_depth(self):
        return max(self.qubit_depth.values())